### ISSUE TITLE
updateGtfsRealtime doesn't work if one URL is down

### ISSUE THREAD

**Issue by nukeador** [BlinkTagInc/node-gtfs#163]
If one realtime URL in your config is down or returns an error, updateGtfsRealtime is not able to import the rest of the valid URLs and breaks execution. 

```
Error: Couldn’t download files
    at downloadGtfsRealtimeData (file:///usr/src/app/node_modules/gtfs/lib/import.js:61:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateRealtimeData (file:///usr/src/app/node_modules/gtfs/lib/import.js:193:30)
    at async file:///usr/src/app/node_modules/gtfs/lib/import.js:744:9
    at async Promise.all (index 0)
    at async Module.updateGtfsRealtime (file:///usr/src/app/node_modules/gtfs/lib/import.js:729:5)
    at async updateGtfsCache (/usr/src/app/lib/gtfs/index.js:77:5)
    at async Timeout._onTimeout (/usr/src/app/lib/gtfs/index.js:45:9)
```

Failing config URLs should fail graciously and just return a console error/warning.

**Comment by brendannee** [comment]
Great idea. Try out version 4.1.1 that I just released https://github.com/BlinkTagInc/node-gtfs/releases/tag/4.11.1 - let me know if this works as you expected.

**Comment by nukeador** [comment]
It seems it works well, thanks!
