### ISSUE TITLE
Import error on large dataset

### ISSUE THREAD

**Issue by graycrow** [BlinkTagInc/node-gtfs#76]
I'm trying to import a relatively large dataset for Prague Public Transport System. Import throws an error (TypeError: Invalid data, chunk must be a string or buffer, not object) at `Importing - stop_times.txt ` step. The file size is 74M and it has about 2M lines. Import hangs every time on different but large and round line number (xxx lines imported). I've seen values like 400000, 500000 670000 lines.

OS: Windows Server 2012R2
Node: 8.1.3
gtfs: 0.11.0
mongo db: v2.4.3

My config.json
```
{
    "agencies": [
        {
            "agency_key": "DPP",
            "exclude": [
                "fare_attributes",
                "fare_rules",
                "feed_info",
                "frequencies",
                "shapes"
            ],
            "url": "http://opendata.iprpraha.cz/DPP/JR/jrdata.zip"
        }
    ],
    "mongoUrl": "mongodb://localhost:27017/gtfs",
    "skipDelete": false,
    "verbose": true
}
```

Node output
```
D:\GRAYCROW\PROJECTS\IDOS\gtfs\dist>node index.js
Starting GTFS import for 1 file
DPP: Downloading GTFS from http://opendata.iprpraha.cz/DPP/JR/jrdata.zip
DPP: Download successful
DPP: Importing GTFS from D:\GRAYCROW\PROJECTS\IDOS\gtfs\dist\downloads/DPP-gtfs.zip
DPP: Importing - agency.txt - 17 lines imported
DPP: Importing - calendar_dates.txt - 72 lines imported
DPP: Importing - calendar.txt - 70 lines imported
DPP: Skipping - fare_attributes.txt
DPP: Skipping - fare_rules.txt
DPP: Skipping - feed_info.txt
DPP: Skipping - frequencies.txt
DPP: Importing - routes.txt - 387 lines imported
DPP: Skipping - shapes.txt
D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb\lib\utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:696:11)
    at text (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\lib\import.js:283:70)
    at importLines (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\lib\import.js:232:17)
    at bulk.execute.err (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\lib\import.js:74:5)
    at handleCallback (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb\lib\utils.js:120:56)
    at D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb\lib\bulk\unordered.js:462:22
    at handleCallback (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb\lib\utils.js:120:56)
    at resultHandler (D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb\lib\bulk\unordered.js:408:11)
    at D:\GRAYCROW\PROJECTS\IDOS\gtfs\node_modules\gtfs\node_modules\mongodb-core\lib\wireprotocol\2_4_support.js:538:34
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

Mongo output
```
C:\mongodb\bin\mongod.exe --help for help and startup options
Tue Jul 04 15:22:44.713 [initandlisten] MongoDB starting : pid=11428 port=27017 dbpath=\data\db\ 64-bit host=endurance
Tue Jul 04 15:22:44.714 [initandlisten] db version v2.4.3
Tue Jul 04 15:22:44.714 [initandlisten] git version: fe1743177a5ea03e91e0052fb5e2cb2945f6d95f
Tue Jul 04 15:22:44.714 [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1'
) BOOST_LIB_VERSION=1_49
Tue Jul 04 15:22:44.714 [initandlisten] allocator: system
Tue Jul 04 15:22:44.715 [initandlisten] options: {}
Tue Jul 04 15:22:44.720 [initandlisten] journal dir=\data\db\journal
Tue Jul 04 15:22:44.721 [initandlisten] recover : no journal files present, no recovery needed
Tue Jul 04 15:22:44.746 [initandlisten] waiting for connections on port 27017
Tue Jul 04 15:22:44.746 [websvr] admin web console waiting for connections on port 28017
Tue Jul 04 15:22:48.928 [initandlisten] connection accepted from 127.0.0.1:58287 #1 (1 connection now open)
Tue Jul 04 15:22:48.928 [initandlisten] connection accepted from 127.0.0.1:58288 #2 (2 connections now open)
Tue Jul 04 15:22:48.943 [initandlisten] connection accepted from 127.0.0.1:58289 #3 (3 connections now open)
Tue Jul 04 15:22:48.943 [initandlisten] connection accepted from 127.0.0.1:58290 #4 (4 connections now open)
Tue Jul 04 15:22:48.943 [initandlisten] connection accepted from 127.0.0.1:58291 #5 (5 connections now open)
Tue Jul 04 15:22:48.959 [initandlisten] connection accepted from 127.0.0.1:58292 #6 (6 connections now open)
Tue Jul 04 15:22:53.743 [initandlisten] connection accepted from 127.0.0.1:58294 #7 (7 connections now open)
Tue Jul 04 15:22:53.743 [initandlisten] connection accepted from 127.0.0.1:58295 #8 (8 connections now open)
Tue Jul 04 15:22:53.743 [initandlisten] connection accepted from 127.0.0.1:58296 #9 (9 connections now open)
Tue Jul 04 15:22:53.743 [initandlisten] connection accepted from 127.0.0.1:58297 #10 (10 connections now open)
Tue Jul 04 15:23:10.748 [conn7] remove gtfs.stoptimes query: { agency_key: "DPP" } ndeleted:510000 keyUpdates:0 numYields: 977 locks(micros) w:31485811 1
6995ms
Tue Jul 04 15:23:44.926 [conn8] insert gtfs.stoptimes ninserted:1 keyUpdates:0 locks(micros) w:83 157ms
Tue Jul 04 15:23:44.926 [conn7] insert gtfs.stoptimes ninserted:1 keyUpdates:0 locks(micros) w:157652 157ms
Tue Jul 04 15:24:00.325 [conn4] end connection 127.0.0.1:58290 (9 connections now open)
Tue Jul 04 15:24:05.430 [conn5] end connection 127.0.0.1:58291 (8 connections now open)
Tue Jul 04 15:24:10.609 [conn6] end connection 127.0.0.1:58292 (7 connections now open)
Tue Jul 04 15:24:15.917 [conn1] end connection 127.0.0.1:58287 (6 connections now open)
Tue Jul 04 15:24:20.927 [conn3] end connection 127.0.0.1:58289 (5 connections now open)
Tue Jul 04 15:25:45.895 [conn7] end connection 127.0.0.1:58294 (4 connections now open)
Tue Jul 04 15:25:45.898 [conn8] end connection 127.0.0.1:58295 (3 connections now open)
Tue Jul 04 15:25:45.914 [conn2] end connection 127.0.0.1:58288 (2 connections now open)
Tue Jul 04 15:25:45.914 [conn9] end connection 127.0.0.1:58296 (2 connections now open)
Tue Jul 04 15:25:45.914 [conn10] end connection 127.0.0.1:58297 (2 connections now open)
```

**Comment by brendannee** [comment]
Thanks for reporting this issue. I'm having trouble actually downloading the GTFS file at http://opendata.iprpraha.cz/DPP/JR/jrdata.zip - something is preventing the download. Can you post the GTFS that you are using at a different URL so I can try it out?

**Comment by graycrow** [comment]
I have sent jrdata.zip via WeTransfer.com, you should receive a email to the address listed in your profile.

**Comment by brendannee** [comment]
I just tried this out with the new 1.0.0 version of node-gtfs and it worked!

So grab the latest version and let me know if you still have issues.

**Comment by umadevisk89** [comment]
I see this error on connecting to ldap server using ldapjs module. Any help appreciated
