### ISSUE TITLE
gtfs import error

### ISSUE THREAD

**Issue by akwatra** [BlinkTagInc/node-gtfs#78]
Hi, 

I was testing the code installed correct and with default agency in config
when i tried to import then following error come:
node version 6.9.2

gtfs-import --configPath ./config.json 
/usr/lib/node_modules/gtfs/lib/import.js:14
const cleanupFiles = async task => {
                           ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/gtfs/lib/gtfs.js:2:20)
    at Module._compile (module.js:570:32)

**Comment by brendannee** [comment]
Hi,


Try updating to node.js version 8.1.4 or newer.
