### ISSUE TITLE
Gtfs-import error

### ISSUE THREAD

**Issue by costular** [BlinkTagInc/node-gtfs#88]
First, I am not used to code with Node.js so maybe I am missing something. However I was researching about tasks, third libraries or something and nothing appeared.

I hope you can help me. It occurs when I try to call this command-line sentence.

`gtfs-import --skipDelete --configPath gtfs-config.json
`

And it shows

```
/usr/local/lib/node_modules/gtfs/lib/import.js:51
const removeDatabase = async task => {
                             ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gtfs/lib/gtfs.js:2:20)
    at Module._compile (module.js:570:32)
```

**Comment by brendannee** [comment]
Try upgrading to node 8 and that should fix this issue.

**Comment by costular** [comment]
It works now. Thanks!.
